Repository ultralytics/yolov3, pull requests merged in 2024-11, with the labels that each got.

#2298 Fix PyPI downloads links
  README.md
  README.zh-CN.md
Labels: documentation

#2300 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: enhancement, devops

#2301 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: devops

#2303 Update ci-testing.yml
  .github/workflows/ci-testing.yml
Labels: devops
