Repository ultralytics/yolov3, pull requests merged in 2024-08, with the labels that each got.

#2267 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: enhancement, dependencies

#2273 Apply Ruff Docstring reformat
  export.py
  models/common.py
  models/experimental.py
  utils/activations.py
  utils/augmentations.py
  utils/callbacks.py
  utils/dataloaders.py
  utils/general.py
  utils/loggers/__init__.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/wandb/wandb_utils.py
  utils/metrics.py
  utils/segment/augmentations.py
  utils/segment/general.py
  utils/triton.py
Labels: documentation, python

#2276 Update README.md
  export.py
  hubconf.py
  models/tf.py
  segment/val.py
  utils/dataloaders.py
  utils/loggers/__init__.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/wandb/wandb_utils.py
  utils/metrics.py
  utils/plots.py
  utils/segment/general.py
  utils/segment/metrics.py
  utils/torch_utils.py
  utils/triton.py
Labels: documentation, python

#2277 Add https://www.reddit.com/r/Ultralytics/ badge
  .github/workflows/merge-main-into-prs.yml
  README.md
  export.py
  models/common.py
  models/experimental.py
  models/tf.py
  models/yolo.py
  utils/__init__.py
  utils/activations.py
  utils/augmentations.py
  utils/dataloaders.py
  utils/general.py
  utils/loggers/__init__.py
  utils/loss.py
  utils/metrics.py
  utils/plots.py
  utils/segment/dataloaders.py
  utils/segment/loss.py
  utils/segment/metrics.py
  utils/torch_utils.py
Labels: enhancement, documentation
