Repository ultralytics/yolov3, pull requests merged in 2024-09, with the labels that each got.

#2279 PyUpgrade 3.8 updates
  classify/predict.py
  detect.py
  segment/predict.py
  utils/metrics.py
Labels: enhancement, python

#2281 [Snyk] Fix for 2 vulnerabilities
  requirements.txt
Labels: dependencies, python

#2284 Ultralytics Code Refactor https://ultralytics.com/actions
  CONTRIBUTING.md
  README.md
  README.zh-CN.md
  utils/flask_rest_api/README.md
  utils/loggers/clearml/README.md
Labels: enhancement, documentation

#2283 [Snyk] Fix for 17 vulnerabilities
  requirements.txt
Labels: dependencies, python
