Repository ultralytics/yolov3, pull requests merged in 2025-01, with the labels that each got.

#2311 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#2312 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#2313 Apply `ruff==0.9.0` formatting
  README.md
  README.zh-CN.md
  classify/predict.py
  classify/train.py
  detect.py
  export.py
  segment/predict.py
  segment/train.py
  train.py
  utils/augmentations.py
  utils/dataloaders.py
  utils/general.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/comet/__init__.py
  utils/loggers/wandb/wandb_utils.py
  utils/loss.py
  utils/segment/augmentations.py
  utils/segment/dataloaders.py
  utils/segment/loss.py
  utils/torch_utils.py
Labels: enhancement, documentation

#2314 Standardize license headers in Python files
  benchmarks.py
  classify/predict.py
  classify/train.py
  classify/val.py
  detect.py
  export.py
  hubconf.py
  models/__init__.py
  models/common.py
  models/experimental.py
  models/tf.py
  models/yolo.py
  segment/predict.py
  segment/train.py
  segment/val.py
  train.py
  utils/__init__.py
  utils/activations.py
  utils/augmentations.py
  utils/autoanchor.py
  utils/autobatch.py
  utils/aws/__init__.py
  utils/aws/resume.py
  utils/callbacks.py
  utils/dataloaders.py
  utils/downloads.py
  utils/flask_rest_api/example_request.py
  utils/flask_rest_api/restapi.py
  utils/general.py
  utils/loggers/__init__.py
  utils/loggers/clearml/README.md
  utils/loggers/clearml/__init__.py
  utils/loggers/clearml/clearml_utils.py
  utils/loggers/clearml/hpo.py
  utils/loggers/comet/__init__.py
  utils/loggers/comet/comet_utils.py
  utils/loggers/comet/hpo.py
  utils/loggers/wandb/__init__.py
  utils/loggers/wandb/wandb_utils.py
  utils/loss.py
  utils/metrics.py
  utils/plots.py
  utils/segment/__init__.py
  utils/segment/augmentations.py
  utils/segment/dataloaders.py
  utils/segment/general.py
  utils/segment/loss.py
  utils/segment/metrics.py
  utils/segment/plots.py
  utils/torch_utils.py
  utils/triton.py
  val.py
Labels: documentation

#2315 Standardize license headers in TOML/YAML files
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/ci-testing.yml
  .github/workflows/cla.yml
  .github/workflows/docker.yml
  .github/workflows/format.yml
  .github/workflows/links.yml
  .github/workflows/merge-main-into-prs.yml
  .github/workflows/stale.yml
  data/Argoverse.yaml
  data/GlobalWheat2020.yaml
  data/ImageNet.yaml
  data/SKU-110K.yaml
  data/VisDrone.yaml
  data/coco.yaml
  data/coco128-seg.yaml
  data/coco128.yaml
  data/hyps/hyp.Objects365.yaml
  data/hyps/hyp.VOC.yaml
  data/hyps/hyp.no-augmentation.yaml
  data/hyps/hyp.scratch-high.yaml
  data/hyps/hyp.scratch-low.yaml
  data/hyps/hyp.scratch-med.yaml
  data/objects365.yaml
  data/voc.yaml
  data/xView.yaml
  models/hub/anchors.yaml
  models/hub/yolov5-bifpn.yaml
  models/hub/yolov5-fpn.yaml
  models/hub/yolov5-p2.yaml
  models/hub/yolov5-p34.yaml
  models/hub/yolov5-p6.yaml
  models/hub/yolov5-p7.yaml
  models/hub/yolov5-panet.yaml
  models/hub/yolov5l6.yaml
  models/hub/yolov5m6.yaml
  models/hub/yolov5n6.yaml
  models/hub/yolov5s-LeakyReLU.yaml
  models/hub/yolov5s-ghost.yaml
  models/hub/yolov5s-transformer.yaml
  models/hub/yolov5s6.yaml
  models/hub/yolov5x6.yaml
  models/segment/yolov5l-seg.yaml
  models/segment/yolov5m-seg.yaml
  models/segment/yolov5n-seg.yaml
  models/segment/yolov5s-seg.yaml
  models/segment/yolov5x-seg.yaml
  models/yolov3-spp.yaml
  models/yolov3-tiny.yaml
  models/yolov3.yaml
  models/yolov5l.yaml
  models/yolov5m.yaml
  models/yolov5n.yaml
  models/yolov5s.yaml
  models/yolov5x.yaml
  pyproject.toml
  utils/google_app_engine/app.yaml
Labels: documentation

#2316 Update links.yml
  .github/workflows/links.yml
Labels: documentation, devops
